# Generated by Django 5.0.6 on 2024-08-27 07:20

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default=myapp.models.generate_product_code, max_length=6, unique=True)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(upload_to='products/')),
                ('image3', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('Salwar-Suit', 'Salwar Suit'), ('Lehnga-Choli', 'Lehnga Choli'), ('Gown', 'Gown'), ('Designer-Suit', 'Designer Suit'), ('Jeans-Tops', 'Jeans Tops')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_s', models.PositiveIntegerField(default=0)),
                ('quantity_m', models.PositiveIntegerField(default=0)),
                ('quantity_l', models.PositiveIntegerField(default=0)),
                ('quantity_xl', models.PositiveIntegerField(default=0)),
                ('quantity_xxl', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
